authapp/urls.py
from django.urls import path

import authapp.views as authapp

app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('register/', authapp.register, name='register'),
    path('profile/', authapp.profile, name='profile'),
    path('logout/', authapp.logout, name='logout'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp

app_name = 'basketapp'

urlpatterns = [
    path('add/<int:id>/', basketapp.basket_add, name='basket_add'),
    path('remove/<int:id>/', basketapp.basket_remove, name='basket_remove'),
    path('edit/<int:id>/<int:quantity>/', basketapp.basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path
from mainapp import views as mainapp_views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', mainapp_views.index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mainapp/urls.py
from django.urls import path
from mainapp import views as mainapp_views

app_name = 'mainapp'

urlpatterns = [
    path('', mainapp_views.products, name='index'),
    path('<int:category_id>/', mainapp_views.products, name='category'),
    path('page/<int:page>/', mainapp_views.products, name='page'),
]

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(max_length=64, unique=True)
    description = models.TextField(blank=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    image = models.ImageField(upload_to='product_images', blank=True)
    description = models.TextField(blank=True)
    short_description = models.CharField(max_length=64, blank=True)
    price = models.DecimalField(max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(default=0)
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'{self.name} {self.category.name}'

mainapp/views.py
from django.shortcuts import render
from mainapp.models import Product, ProductCategory
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


def index(request):
    context = {
        'title': 'GeekShop',
    }
    return render(request, 'mainapp/index.html', context)


def products(request, category_id=None, page=1):
    context = {
        'title': 'GeekShop - Каталог',
        'product_categories': ProductCategory.objects.all(),
    }

    if category_id:
        products = Product.objects.filter(category_id=category_id).order_by('price')
    else:
        products = Product.objects.all().order_by('price')

    paginator = Paginator(products, 3)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context.update({'products': products_paginator})

    return render(request, 'mainapp/products.html', context)

mainapp/templates/mainapp/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>
        {% block title %}{% endblock %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    {% block css %}{% endblock %}

</head>
<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">GeekShop</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог
                        <i class="fas fa-shopping-bag"></i>
                    </a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:profile' %}"> {{ user.first_name }}
                            <i class="fas fa-user-circle"></i>
                        </a>
                    </li>
                    {% if user.is_superuser or user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin_staff:index' %}">
                                <i class="fas fa-users-cog"></i>
                            </a>
                        </li>
                    {% endif %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:logout' %}">Выйти <i class="fas fa-sign-out-alt"></i></a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'auth:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% block content %}
{% block product_card %}{% endblock %}
{% endblock %}

{% block footer %}{% endblock %}

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

<!-- Basket script -->
<script src="{% static 'js/basket.js' %}"></script>

</body>
</html>

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
        {{ title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/index.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <h1 class="mt-5">GeekShop Store</h1>
                    <p>
                        Новые образы и лучшие бренды на GeekShop Store.
                        Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                    </p>
                    <button id="start-purchase-btn" type="button" class="btn btn-lg">
                        <a id="start-purchase-link" href="{% url 'products:index' %}">
                            Начать покупки
                        </a>
                    </button>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mainapp/templates/mainapp/products.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block title %}
    {{ title }}
{% endblock %}

{% block css %}
    <link href="{% static 'css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">GeekShop</h1>
                <div class="list-group">
                    {% for category in product_categories %}
                        {% if category.is_active %}
                            <a href="{% url 'mainapp:category' category.id %}"
                               class="list-group-item">
                                {{ category.name }}
                            </a>
                        {% endif %}
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg"
                                 alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg"
                                 alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg"
                                 alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% block product_card %}
                        {% for product in products %}
                            <div class="col-lg-4 col-md-6 mb-4">
                                <div class="card h-100">
                                    <a href="#">
                                        <img class="card-img-top"
                                             src="/media/{{ product.image }}"
                                             alt="">
                                    </a>
                                    <div class="card-body">
                                        <h4 class="card-title">
                                            <a href="#">{{ product.name }}</a>
                                        </h4>
                                        <h5>{{ product.price }}</h5>
                                        <p class="card-text">{{ product.short_description }}</p>
                                    </div>
                                    <div class="card-footer text-center">
                                        <a href="{% url 'baskets:basket_add' product.id %}">
                                            <button type="button" class="btn btn-outline-success">Отправить в корзину
                                            </button>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    {% endblock %}

                </div>
                <!-- /.row -->
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if not products.has_previous %} # {% else %} {% url 'products:page' products.previous_page_number %} {% endif %}">
                                Предыдущая
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}
                            <li class="page-item">
                                <a class="page-link"
                                   href="{% url 'products:page' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}">
                            <a class="page-link"
                               href="{% if not products.has_next %} # {% else %} {% url 'products:page' products.next_page_number %} {% endif %}">
                                Следующая
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>
            <!-- /.col-lg-9 -->

        </div>
        <!-- /.row -->

    </div>
    <!-- /.container -->
{% endblock %}

{% block footer %}
    <!-- Footer -->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; GeekShop 2020</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}